import { useCallback, useState } from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, RefreshCw, Info } from 'lucide-react';
import { useProfile } from '../hooks/useProfile';
import { generateWorkoutPlan, hasGeminiKey } from '../services/aiCoachService';
import Spinner from '../components/Spinner';
import { GOAL_OPTIONS, LEVEL_OPTIONS, EQUIPMENT_OPTIONS } from '../utils/stats';

export default function Coach() {
  const { profile } = useProfile();
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generate = useCallback(async () => {
    if (loading) return;
    setLoading(true);
    setError('');
    try {
      const result = await generateWorkoutPlan(profile);
      setPlan(result);
    } catch (err) {
      setError(err?.message || 'Could not generate a plan.');
    } finally {
      setLoading(false);
    }
  }, [loading, profile]);

  const goal = GOAL_OPTIONS.find((o) => o.id === profile.goal)?.label;
  const level = LEVEL_OPTIONS.find((o) => o.id === profile.fitnessLevel)?.label;
  const equipment = EQUIPMENT_OPTIONS.find((o) => o.id === profile.equipment)?.label;

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">AI Coach</h1>
          <p className="text-sm text-ink-500">
            Plan tuned for: {goal} · {level} · {equipment}
          </p>
        </div>
        <button onClick={generate} disabled={loading} className="btn-primary">
          {loading ? <Spinner size="sm" label="" /> : <Sparkles className="h-4 w-4" />}
          {plan ? 'Regenerate' : 'Generate plan'}
        </button>
      </div>

      {!hasGeminiKey() && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 flex gap-2 items-start text-sm text-blue-900">
          <Info className="h-4 w-4 flex-shrink-0 mt-0.5" />
          <div>
            Running in offline mode using local rule-based plans. Add{' '}
            <code className="bg-blue-100 px-1 rounded">VITE_GEMINI_API_KEY</code> to{' '}
            <code className="bg-blue-100 px-1 rounded">.env.local</code> for live AI-generated plans.
          </div>
        </div>
      )}

      {!plan && !loading && (
        <div className="card text-center py-10">
          <Sparkles className="h-10 w-10 text-brand-600 mx-auto mb-3" />
          <h2 className="font-semibold mb-1">Ready when you are.</h2>
          <p className="text-sm text-ink-500 mb-5 max-w-md mx-auto">
            Click <em>Generate plan</em> and your coach will build a weekly program.
            Update your profile to tune the recommendation.
          </p>
          <Link to="/profile" className="btn-secondary inline-flex">
            Edit profile
          </Link>
        </div>
      )}

      {loading && (
        <div className="card flex items-center gap-3 py-10 justify-center">
          <Spinner size="lg" />
        </div>
      )}

      {error && (
        <div className="card border-red-200 text-red-700 flex items-center gap-3">
          <RefreshCw className="h-4 w-4" />
          <p className="text-sm">{error}</p>
        </div>
      )}

      {plan && !loading && (
        <div className="space-y-4">
          <div className="card bg-gradient-to-r from-brand-50 to-white border-brand-100">
            <div className="flex items-start gap-3">
              <Sparkles className="h-5 w-5 text-brand-600 flex-shrink-0 mt-0.5" />
              <div>
                <h2 className="font-semibold">This week's focus</h2>
                <p className="text-sm text-ink-700 mt-1">{plan.summary}</p>
                <p className="text-[11px] text-ink-500 mt-2 uppercase tracking-wide">
                  Generated by: {plan.source}
                </p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {plan.days.map((day) => (
              <div key={day.day} className="card">
                <div className="flex items-baseline justify-between mb-3">
                  <h3 className="font-semibold">{day.day}</h3>
                  <span className="text-xs text-ink-500">{day.focus}</span>
                </div>
                <ul className="space-y-2">
                  {day.exercises.map((ex) => (
                    <li key={`${day.day}-${ex.name}`} className="text-sm flex items-baseline justify-between gap-2 py-1 border-b border-ink-300/30 last:border-0">
                      <span className="font-medium">{ex.name}</span>
                      <span className="text-xs text-ink-500 flex-shrink-0">
                        {ex.sets}×{ex.reps}{ex.rest && ex.rest !== '-' ? ` · rest ${ex.rest}` : ''}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          {plan.tips?.length > 0 && (
            <div className="card">
              <h3 className="font-semibold mb-2">Coach tips</h3>
              <ul className="text-sm text-ink-700 space-y-1 list-disc pl-5">
                {plan.tips.map((tip) => <li key={tip}>{tip}</li>)}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
